name: experimental_testing_app
publish_to: 'none'
version: 0.1.0

environment:
  flutter: 3.28.0-2.0.pre.38596
  sdk: 3.7.0-267.0.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
