name: Flutter test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Flutter version
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3

      - name: Run tests
        run: flutter test --experimental-faster-testing
